
# Site settings
title: Nuit Universitaire Ludique Libre
email: abl-ca@univ-lille1.fr
url: http://bidouilleurslibristes.github.io/
description: "
La Nuit Universitaire Ludique Libre <br> 25-26 mai - Cité Scientifique - Université de Lille
<p>2 jours consacrés au(x) jeu(x) libre(s) ou indépendant(s), proposés par l'Association des Bidouilleurs Libristes. L'objectif de cette Nuit Universitaire Ludique Libre (dire la NULL !) est de promouvoir le « libre » au sens large par et/ou pour le(s) jeu(x).</p>"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Bidouilleurs Libristes

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
